/*
Julio César Rodríguez Figueroa A01029680
Generador de un edificio en formato OBJ.
Valores por defecto: 8, 6.0, 1.0, 0.8
*/

import * as fs from 'fs'; // Manejo de archivos
import { V3 } from '../libs/3d-lib.js'; // Librería para vectores 3D

function writeOBJ(filename, vertices, normals, faces) { // Escribe el archivo OBJ, metiendo los vértices, normales y caras
    let out = '# OBJ generated by buildingGenerator_fixed.js\n';
    // Escribir vértices
    for (let i = 0; i < vertices.length; i++) {
        const v = vertices[i];
        out += `v ${v[0]} ${v[1]} ${v[2]}\n`;
    }
    // Escribir normales
    for (let i = 0; i < normals.length; i++) {
        const n = normals[i];
        out += `vn ${n[0]} ${n[1]} ${n[2]}\n`;
    }
    // Escribir caras (f v//vn)
    for (let i = 0; i < faces.length; i++) {
        const f = faces[i];
        out += 'f ' + f.map(p => `${p.v}//${p.n}`).join(' ') + '\n';
    }
    fs.writeFileSync(filename, out, 'utf8');
}

function pushVertex(v, n, vertices, normals) { // Agrega vértice y normal, devuelve índices del vértice y la normal
    vertices.push(v);
    normals.push(n);
    return { v: vertices.length, n: normals.length };
}

function generateBuilding(sides = 8, height = 6.0, baseRadius = 1.0, topRadius = 0.8) {
    const vertices = [];
    const normals = [];
    const faces = [];

    // Normales para las tapas
    const baseNormal = V3.create(0, -1, 0);
    const topNormal = V3.create(0, 1, 0);

    // Centro de la base
    const baseCenter = pushVertex(V3.create(0, 0, 0), baseNormal, vertices, normals);

    const baseRing = [];
    const sideLower = [];
    const sideUpper = [];
    const topRing = [];

    const twoPi = Math.PI * 2;
    const k = baseRadius - topRadius; // Diferencia de radios para la normal lateral

    for (let i = 0; i < sides; i++) {
        const a = (i / sides) * twoPi;
        const cosA = Math.cos(a);
        const sinA = Math.sin(a);

        const bx = cosA * baseRadius;
        const bz = sinA * baseRadius;
        const tx = cosA * topRadius;
        const tz = sinA * topRadius;

        // Vertice de la tapa inferior
        baseRing.push(pushVertex(V3.create(bx, 0, bz), baseNormal, vertices, normals));

        // Normal lateral
        const sideNormal = V3.normalize(V3.create(cosA * height, k, sinA * height));

        sideLower.push(pushVertex(V3.create(bx, 0, bz), sideNormal, vertices, normals));
        sideUpper.push(pushVertex(V3.create(tx, height, tz), sideNormal, vertices, normals));

        // Vertice de la tapa superior
        topRing.push(pushVertex(V3.create(tx, height, tz), topNormal, vertices, normals));
    }

    // Centro de la tapa superior
    const topCenter = pushVertex(V3.create(0, height, 0), topNormal, vertices, normals);

    // Caras de la base
    for (let i = 0; i < sides; i++) {
        const next = (i + 1) % sides;
        faces.push([
            { v: baseCenter.v, n: baseCenter.n },
            { v: baseRing[next].v, n: baseRing[next].n },
            { v: baseRing[i].v, n: baseRing[i].n }
        ]);
    }

    // Caras de la tapa superior
    for (let i = 0; i < sides; i++) {
        const next = (i + 1) % sides;
        faces.push([
            { v: topCenter.v, n: topCenter.n },
            { v: topRing[i].v, n: topRing[i].n },
            { v: topRing[next].v, n: topRing[next].n }
        ]);
    }

    // Caras laterales
    for (let i = 0; i < sides; i++) {
        const next = (i + 1) % sides;
        const a = sideLower[i];
        const b = sideLower[next];
        const c = sideUpper[next];
        const d = sideUpper[i];

        // a-b-c
        faces.push([
            { v: a.v, n: a.n },
            { v: b.v, n: b.n },
            { v: c.v, n: c.n }
        ]);

        // a-c-d
        faces.push([
            { v: a.v, n: a.n },
            { v: c.v, n: c.n },
            { v: d.v, n: d.n }
        ]);
    }

    // Escribir archivo OBJ. NOTA: para simplificar, siempre se usa el mismo nombre, en caso de querer otro objeto cambiar aquí
    const filename = `building_1.obj`;
    writeOBJ(filename, vertices, normals, faces);
    console.log(`OBJ escrito: ${filename}`);
}

// Para poder usar números desde la consola
const args = process.argv.slice(2);
const sides = args[0] ? parseInt(args[0], 10) : 8;
const height = args[1] ? parseFloat(args[1]) : 6.0;
const baseRadius = args[2] ? parseFloat(args[2]) : 1.0;
const topRadius = args[3] ? parseFloat(args[3]) : 0.8;

generateBuilding(sides, height, baseRadius, topRadius);